### ISSUE TITLE
vendor creates files owned by root

### ISSUE THREAD

**Issue by funnylookinhat** [treeder/go#2]
This is an awesome tool!  Thanks for building it.

I noticed that when I run `docker run --rm -v $PWD:/myApp -w /myApp treeder/go vendor` it creates a directory for vendor'd assets that is owned by root and have 777 permissions - similarly, built applications are owned by root and are 777.  Shouldn't those be owned by whichever user is using the docker tool?  i.e. I'm running as a normal user who's been added to the docker group - so I would expect those resulting files to have the same permissions as the files I created to be used with the tool.

```
$ ls -l
total 6256
-rwxrwxrwx 1 root           root           6397008 Aug 30 06:57 myApp
-rw-rw-r-- 1 funnylookinhat funnylookinhat     337 Aug 30 06:55 myApp.go
drwxrwxrwx 4 root           root              4096 Aug 30 06:55 vendor
```

I would have expected this:

```
$ ls -l
total 6256
-rwxrwxr-x 1 funnylookinhat funnylookinhat     6397008 Aug 30 06:57 myApp
-rw-rw-r-- 1 funnylookinhat funnylookinhat     337 Aug 30 06:55 myApp.go
drwxrwxr-x 4 funnylookinhat funnylookinhat    4096 Aug 30 06:55 vendor
```

Might seem trivial - but in my experience, permissions should never be taken for granted. :)

**Comment by treeder** [comment]
Thanks!  Glad you like it.

Unfortunately Docker runs as root so it creates the new files as the root user. I chmod them to make them accessible to everyone before returning. It would be nice to keep the same user, but not sure how to do that since inside the container you don't know who it is.

**Comment by funnylookinhat** [comment]
Yeah my intermittent digging hasn't been able to find a way to get around this either.  Thanks for the help!
