### ISSUE TITLE
Vendoring Issues

### ISSUE THREAD

**Issue by onlydole** [treeder/go#5]
I get this error when trying to vendor my dependencies (from GitHub and local sources).

```
Vendoring dependencies...
# x/y/z
./main.go:31: illegal NUL byte
./main.go:32: illegal character 0x0
./main.go:32: illegal NUL byte
./main.go:32: illegal character 0x0
./main.go:32: illegal NUL byte
./main.go:32: illegal character 0x0
./main.go:32: illegal NUL byte
./main.go:32: illegal character 0x0
./main.go:32: illegal NUL byte
./main.go:32: illegal character 0x0
./main.go:32: too many errors
```

I even tried your code and I am getting some newline errors when I tried your app.go example.

**Comment by treeder** [comment]
Strange, what OS are you on?

**Comment by onlydole** [comment]
OS X Yosemite with Go 1.5 installed natively (I know this doesn't matter), and Docker 1.8.1

**Comment by onlydole** [comment]
With a completely empty main function, I get this: 

```
# x/y/z
./main.go:11: newline in string
./main.go:11: syntax error: unexpected semicolon or newline, expecting )
```

Is that something to do with the shell file?

**Comment by treeder** [comment]
Can you paste your main.go here so I can try it?

**Comment by onlydole** [comment]
Absolutely!

```
package main

import (
  "fmt"
  "log"
  "net/http"

  "github.com/gorilla/mux"
)

func main() {
  r := mux.NewRouter()
  r.HandleFunc("/", Hello)
  http.Handle("/", r)
  fmt.Println("Starting up on 8080")
  log.Fatal(http.ListenAndServe(":8080", nil))
}

func Hello(w http.ResponseWriter, req *http.Request) {
  fmt.Fprintln(w, "Hello world!")
}
```

The error I get with that code is this:

```
Vendoring dependencies...
# x/y/z
./main.go:20: newline in string
./main.go:20: syntax error: unexpected semicolon or newline, expecting )
```

**Comment by onlydole** [comment]
I am testing inside of my local $GOPATH (/home/user/go/src/app), is that an issue?

**Comment by onlydole** [comment]
I was able to get it to work outside of that directory, but it doesn't play nice with local, nested package dependencies.

**Comment by treeder** [comment]
It worked when you copied it outside your local GOPATH? That's strange, it shouldn't know anything about your local GOPATH.

**Comment by onlydole** [comment]
It did work outside my local GOPATH, and it doesn't seem to like when I import local dependency packages (ex. MyAppName/utils)

**Comment by treeder** [comment]
Can you do a `docker pull treeder/go` then try this new -e param:

```
docker run --rm -it -v "$PWD":/app -w /app -e "SRCPATH=github.com/username/reponame" treeder/go vendor
```

You can define SRCPATH if you have local packages.

**Comment by onlydole** [comment]
I got this when running that (my packages are local only right now, I won't be able to put them up publicly due to the nature of the project) 

```
creds defined
total 12
drwx------    2 root     root          4096 Sep 10 01:48 .
drwxr-xr-x   47 root     root          4096 Sep 10 01:48 ..
-rw-r--r--    1 root     root             1 Sep 10 01:48 .git-credentials

gitconfig defined
total 16
drwx------    2 root     root          4096 Sep 10 01:48 .
drwxr-xr-x   47 root     root          4096 Sep 10 01:48 ..
-rw-r--r--    1 root     root             1 Sep 10 01:48 .git-credentials
-rw-r--r--    1 root     root             1 Sep 10 01:48 .gitconfig

Vendoring dependencies...
package MyApp/handlers: unrecognized import path "MyApp/handlers"
```

**Comment by treeder** [comment]
Is your code in `$GOPATH/src/MyApp` ?  If so, can you set SRCPATH=MyApp and try it?  Also, do another docker pull to get rid of that creds output.

**Comment by onlydole** [comment]
That did it! Thank you so much!!!
